### ISSUE TITLE
build failure on flutter 2.8

### ISSUE THREAD

**Issue by RegNex** [fluttercandies/extended_image#437]
After upgrading to the latest version of flutter(v2.8), my project fails to build on Android and iOS. 
Below is the logs:

```
[+2396 ms] > Task :app:compileFlutterBuildDebug
[        ] [ +137 ms] executing: sysctl hw.optional.arm64
[        ] [  +27 ms] Exit code 1 from: sysctl hw.optional.arm64
[        ] [        ] sysctl: unknown oid 'hw.optional.arm64'
[        ] [   +9 ms] executing: [/Users/etornam/Development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +17 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] cf4400006550b70f28e4b4af815151d1e74846c6
[        ] [        ] executing: [/Users/etornam/Development/flutter/] git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[        ] [  +32 ms] Exit code 0 from: git tag --points-at cf4400006550b70f28e4b4af815151d1e74846c6
[        ] [        ] 2.8.0
[        ] [  +12 ms] executing: [/Users/etornam/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/Users/etornam/Development/flutter/] git ls-remote --get-url origin
[        ] [  +15 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +92 ms] executing: [/Users/etornam/Development/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [   +8 ms] executing: sw_vers -productName
[        ] [  +16 ms] Exit code 0 from: sw_vers -productName
[        ] [        ] macOS
[        ] [        ] executing: sw_vers -productVersion
[        ] [  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] [        ] 12.0.1
[        ] [        ] executing: sw_vers -buildVersion
[        ] [  +17 ms] Exit code 0 from: sw_vers -buildVersion
[        ] [        ] 21A559
[        ] [  +72 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +145 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[        ] [  +67 ms] Initializing file store
[        ] [  +32 ms] Skipping target: gen_localizations
[        ] [  +25 ms] gen_dart_plugin_registrant: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
/Users/etornam/Projects/FlutterProjects/african_observation_app/.dart_tool/package_config_subset}
[        ] [  +52 ms] Found plugin app_tracking_transparency at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/app_tracking_transparency-2.0.2+1/
[        ] [  +12 ms] Found plugin audio_session at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/audio_session-0.1.6+1/
[        ] [  +17 ms] Found plugin cloud_firestore at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-3.1.4/
[        ] [   +4 ms] Found plugin cloud_firestore_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-2.6.4/
[        ] [   +2 ms] Found plugin connectivity at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/connectivity-3.0.6/
[        ] [   +2 ms] Found plugin connectivity_for_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/connectivity_for_web-0.4.0+1/
[        ] [   +1 ms] Found plugin connectivity_macos at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/connectivity_macos-0.2.1+2/
[        ] [  +16 ms] Found plugin firebase_analytics at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_analytics-9.0.2/
[        ] [   +2 ms] Found plugin firebase_analytics_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_analytics_web-0.4.0+2/
[        ] [   +1 ms] Found plugin firebase_core at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.10.5/
[        ] [   +2 ms] Found plugin firebase_core_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-1.5.2/
[        ] [   +1 ms] Found plugin firebase_crashlytics at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.4.3/
[        ] [   +2 ms] Found plugin firebase_dynamic_links at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_dynamic_links-4.0.2/
[        ] [   +1 ms] Found plugin firebase_in_app_messaging at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.6.0+4/
[        ] [   +1 ms] Found plugin firebase_messaging at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.3/
[        ] [   +2 ms] Found plugin firebase_messaging_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_web-2.2.4/
[        ] [   +1 ms] Found plugin firebase_remote_config at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-1.0.2/
[        ] [   +2 ms] Found plugin firebase_remote_config_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config_web-1.0.2/
[        ] [  +14 ms] Found plugin flutter_local_notifications at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/flutter_local_notifications-9.1.5/
[        ] [   +8 ms] Found plugin flutter_pdfview at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/flutter_pdfview-1.2.1/
[        ] [   +1 ms] Found plugin flutter_plugin_android_lifecycle at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-2.0.2/
[        ] [  +11 ms] Found plugin image_cropper at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.4.1/
[        ] [   +1 ms] Found plugin image_picker at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/image_picker-0.8.4+4/
[        ] [   +1 ms] Found plugin image_picker_for_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/image_picker_for_web-2.1.3/
[        ] [   +5 ms] Found plugin just_audio at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/just_audio-0.9.18/
[        ] [   +2 ms] Found plugin just_audio_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/just_audio_web-0.4.2/
[        ] [  +12 ms] Found plugin open_file at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/open_file-3.2.1/
[        ] [   +1 ms] Found plugin package_info at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/package_info-2.0.2/
[        ] [   +4 ms] Found plugin path_provider at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider-2.0.8/
[        ] [   +1 ms] Found plugin path_provider_android at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.9/
[        ] [   +1 ms] Found plugin path_provider_ios at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider_ios-2.0.7/
[        ] [   +1 ms] Found plugin path_provider_linux at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider_linux-2.0.2/
[        ] [   +2 ms] Found plugin path_provider_macos at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-2.0.2/
[        ] [   +2 ms] Found plugin path_provider_windows at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/path_provider_windows-2.0.3/
[        ] [   +3 ms] Found plugin permission_handler at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/permission_handler-8.3.0/
[        ] [   +4 ms] Found plugin pusher_client at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/pusher_client-2.0.0/
[        ] [   +1 ms] Found plugin quick_actions at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/quick_actions-0.6.0+8/
[        ] [   +4 ms] Found plugin share at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/share-2.0.4/
[        ] [   +1 ms] Found plugin shared_preferences at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/shared_preferences-2.0.7/
[        ] [   +1 ms] Found plugin shared_preferences_linux at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/shared_preferences_linux-2.0.2/
[        ] [   +1 ms] Found plugin shared_preferences_macos at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-2.0.2/
[        ] [   +1 ms] Found plugin shared_preferences_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-2.0.2/
[        ] [        ] Found plugin shared_preferences_windows at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/shared_preferences_windows-2.0.2/
[        ] [   +2 ms] Found plugin sqflite at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/sqflite-2.0.0+4/
[        ] [   +8 ms] Found plugin url_launcher at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher-6.0.17/
[        ] [        ] Found plugin url_launcher_android at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_android-6.0.13/
[        ] [        ] Found plugin url_launcher_ios at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_ios-6.0.13/
[        ] [        ] Found plugin url_launcher_linux at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_linux-2.0.1/
[        ] [   +1 ms] Found plugin url_launcher_macos at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-2.0.1/
[        ] [   +1 ms] Found plugin url_launcher_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-2.0.4/
[        ] [        ] Found plugin url_launcher_windows at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/url_launcher_windows-2.0.2/
[        ] [   +1 ms] Found plugin video_player at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/video_player-2.2.7/
[        ] [   +1 ms] Found plugin video_player_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/video_player_web-2.0.3/
[        ] [        ] Found plugin wakelock at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/wakelock-0.5.3+3/
[        ] [        ] Found plugin wakelock_macos at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/wakelock_macos-0.1.0+2/
[        ] [   +1 ms] Found plugin wakelock_web at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/wakelock_web-0.2.0+2/
[        ] [   +1 ms] Found plugin webview_flutter at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/webview_flutter-3.0.0/
[        ] [        ] Found plugin webview_flutter_android at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/webview_flutter_android-2.8.0/
[        ] [   +1 ms] Found plugin webview_flutter_wkwebview at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.0/
[        ] [        ] Found plugin wifi_info_flutter at /Users/etornam/.pub-cache/hosted/pub.dartlang.org/wifi_info_flutter-2.0.2/
[        ] [  +38 ms] gen_dart_plugin_registrant: Complete
[        ] [   +2 ms] kernel_snapshot: Starting due to {}
[        ] [  +23 ms] /Users/etornam/Development/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/etornam/Development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/etornam/Development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter --no-print-incremental-dependencies
-DFLUTTER_WEB_AUTO_DETECT=true -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --no-link-platform --packages
/Users/etornam/Projects/FlutterProjects/african_observation_app/.dart_tool/package_config.json --output-dill
/Users/etornam/Projects/FlutterProjects/african_observation_app/.dart_tool/flutter_build/12049f001896026e0eb99f2fad4d1e95/app.dill --depfile
/Users/etornam/Projects/FlutterProjects/african_observation_app/.dart_tool/flutter_build/12049f001896026e0eb99f2fad4d1e95/kernel_snapshot.d
/Users/etornam/Projects/FlutterProjects/african_observation_app/.dart_tool/flutter_build/generated_main.dart
[+6824 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the name
'delta'.
[        ]           delta: delta,
[        ]           ^^^^^
[  +17 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional arguments: 2
required, 1 given.
[        ]           focalPointDelta > computePanSlop(pointerDeviceKind))
[        ]                                           ^
[        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Context: Found this candidate, but the arguments don't match.
[        ] double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ]        ^^^^^^^^^^^^^^
[   +2 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments: 2
required, 1 given.
[        ]     final double minDistance = minFlingDistance ?? computeHitSlop(kind);
[        ]                                                                  ^
[        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
[        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ]        ^^^^^^^^^^^^^^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments: 2
required, 1 given.
[        ]     return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
[        ]                                                       ^
[        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
[        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ]        ^^^^^^^^^^^^^^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional arguments: 2
required, 1 given.
[        ]     final double minDistance = minFlingDistance ?? computeHitSlop(kind);
[        ]                                                                  ^
[        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
[        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ]        ^^^^^^^^^^^^^^
[        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional arguments: 2
required, 1 given.
[        ]     return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
[        ]                                                       ^
[        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
[        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ]        ^^^^^^^^^^^^^^
[ +428 ms] ../../../.pub-cache/hosted/pub.dartlang.org/settings_ui-1.0.0/lib/src/cupertino_settings_item.dart:76:51: Error: A value of type 'ListTileThemeData' can't
be assigned to a variable of type 'ListTileTheme'.
[        ]  - 'ListTileThemeData' is from 'package:flutter/src/material/list_tile.dart'
('../../../Development/flutter/packages/flutter/lib/src/material/list_tile.dart').
[        ]  - 'ListTileTheme' is from 'package:flutter/src/material/list_tile.dart'
('../../../Development/flutter/packages/flutter/lib/src/material/list_tile.dart').
[        ]     final ListTileTheme tileTheme = ListTileTheme.of(context);
[        ]                                                   ^
[+4796 ms] [+12534 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the
name 'delta'.
[        ] [   +2 ms]           delta: delta,
[        ] [        ]           ^^^^^
[        ] [  +10 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional
arguments: 2 required, 1 given.
[        ] [        ]           focalPointDelta > computePanSlop(pointerDeviceKind))
[        ] [        ]                                           ^
[        ] [        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Context: Found this candidate, but the arguments don't
match.
[        ] [        ] double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ] [        ]        ^^^^^^^^^^^^^^
[        ] [   +2 ms] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments:
2 required, 1 given.
[        ] [        ]     final double minDistance = minFlingDistance ?? computeHitSlop(kind);
[        ] [        ]                                                                  ^
[        ] [        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't
match.
[        ] [        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ] [        ]        ^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments:
2 required, 1 given.
[        ] [        ]     return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
[        ] [        ]                                                       ^
[        ] [        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't
match.
[        ] [        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ] [        ]        ^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional
arguments: 2 required, 1 given.
[        ] [        ]     final double minDistance = minFlingDistance ?? computeHitSlop(kind);
[        ] [        ]                                                                  ^
[   +9 ms] [        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't
match.
[        ] [        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ] [        ]        ^^^^^^^^^^^^^^
[        ] [        ] ../../../.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional
arguments: 2 required, 1 given.
[        ] [        ]     return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
[        ] [        ]                                                       ^
[        ] [        ] ../../../Development/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't
match.
[        ] [        ] double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
[        ] [        ]        ^^^^^^^^^^^^^^
[ +380 ms] [ +431 ms] ../../../.pub-cache/hosted/pub.dartlang.org/settings_ui-1.0.0/lib/src/cupertino_settings_item.dart:76:51: Error: A value of type
'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.
[        ] [        ]  - 'ListTileThemeData' is from 'package:flutter/src/material/list_tile.dart'
('../../../Development/flutter/packages/flutter/lib/src/material/list_tile.dart').
[        ] [        ]  - 'ListTileTheme' is from 'package:flutter/src/material/list_tile.dart'
('../../../Development/flutter/packages/flutter/lib/src/material/list_tile.dart').
[        ] [        ]     final ListTileTheme tileTheme = ListTileTheme.of(context);
[        ] [        ]                                                   ^
[+7698 ms] [+7703 ms] Persisting file store
[        ] [   +4 ms] Done persisting file store
[        ] [   +4 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/common.dart:241:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +8 ms]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[  +90 ms] [  +15 ms] "flutter assemble" took 21,335ms.
[        ] [   +6 ms]
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:94:3)
[        ]            <asynchronous suspension>
[ +195 ms] [ +253 ms] ensureAnalyticsSent: 252ms
[        ] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] > Task :app:compileFlutterBuildDebug FAILED
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings
[        ] 1 actionable task: 1 executed
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/etornam/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1070
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/etornam/Development/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 25s
[ +447 ms] Running Gradle task 'assembleDebug'... (completed in 25.9s)
[   +4 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +2 ms] "flutter run" took 31,743ms.
[   +4 ms]
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:674:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +254 ms] ensureAnalyticsSent: 252ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1
```

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_image/issues/400
