### ISSUE TITLE
[Error] FadeTransition and loadStateChanged while changing page will cause an error

### ISSUE THREAD

**Issue by samuelg123** [fluttercandies/extended_image#54]
Hi,
I found a problem when using FadeTransition. When the animation controller still playing and move to another page, it will cause an error (see Logs). My suggestion is to wrap all setState in extended_image.dart with `if(mounted) { setState(); }`.
Thank you.

## Code
```
case LoadState.completed: 
   _controller.forward();
   return FadeTransition(
              opacity: _controller,
              child: ExtendedRawImage(
                image: state.extendedImageInfo?.image,
                width: someWidth,
                height: someHeight,
              ),
            )
```

## Logs
```
════════ Exception Caught By image resource service ════════════════════════════════════════════════
The following assertion was thrown when reporting an error to an image listener:
setState() called after dispose(): _ExtendedImageState#37bb5(lifecycle state: defunct, not mounted, stream: ImageStream#ae287(MultiFrameImageStreamCompleter#765d0, [512×512] @ 1.0x, 2 listeners), pixels: null)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1105:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1140:6)
#2      _ExtendedImageState._loadFailed (package:extended_image/src/extended_image.dart:698:5)
#3      ImageStreamCompleter.reportError (package:flutter/src/painting/image_stream.dart:474:24)
#4      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:409:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by samuelg123** [comment]
It seems to be fixed. Sorry I took the wrong version.
