### ISSUE TITLE
[web]Flutter 3.7 , Not supported --web-renderer  html 

### ISSUE THREAD

**Issue by sunjianan9900** [fluttercandies/extended_image#545]
flutter 3.7
extended_image: ^6.3.4

Use the command:  flutter build web --web-renderer html                    

```
 flutter build web --web-renderer html                    

💪 Building with sound null safety 💪

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
lib/common/utils/flutter_textfield_autocomplete.dart:352:15:
Warning: Operand of null-aware operation '!' has type 'OverlayState' which excludes null.
 - 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart'
 ('../../../../SDK/BETA/flutter/packages/flutter/lib/src/widgets/overlay.dart').
      Overlay.of(context)!.insert(listSuggestionsEntry!);
              ^
/Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/extended_image-6.3.4/lib/src/gesture/page_view/widgets/scroll_position.dart:1
22:17:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart'
 ('../../../../SDK/BETA/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
    PageStorage.of(context.storageContext)?.writeState(
                ^
/Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/extended_image-6.3.4/lib/src/gesture/page_view/widgets/scroll_position.dart:1
29:41:
Warning: Operand of null-aware operation '?.' has type 'PageStorageBucket' which excludes null.
 - 'PageStorageBucket' is from 'package:flutter/src/widgets/page_storage.dart'
 ('../../../../SDK/BETA/flutter/packages/flutter/lib/src/widgets/page_storage.dart').
      final double? value = PageStorage.of(context.storageContext)
                                        ^
The compiler crashed: WebSocketException: Connection to 'http://127.0.0.1:61168/PNNQ3i1ouhs=/ws#' was not upgraded to websocket
#0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:320:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#3      _currentHeapCapacity (package:compiler/src/common/ram_usage.dart:27:41)
<asynchronous suspension>
#4      currentHeapCapacityInMb (package:compiler/src/common/ram_usage.dart:38:20)
<asynchronous suspension>
#5      compile.compilationDone (package:compiler/src/dart2js.dart:1090:12)
<asynchronous suspension>
#6      main (package:compiler/src/dart2js.dart:1435:3)
<asynchronous suspension>

vm-service: Error: Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request

Unhandled exception:
WebSocketException: Invalid WebSocket upgrade request


#0      Dart2JSTarget.build (package:flutter_tools/src/build_system/targets/web.dart:225:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:847:9)
<asynchronous suspension>
#2      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:785:32)
<asynchronous suspension>
#6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:614:16)
<asynchronous suspension>
#7      buildWeb (package:flutter_tools/src/web/compile.dart:53:32)
<asynchronous suspension>
#8      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:135:5)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:91:3)
<asynchronous suspension>

```

**Comment by tanveer1302** [comment]
Not sure if my following issue is linked with this but sharing it here because it happens with html renderer only

https://github.com/fluttercandies/extended_image/issues/546#issue-1571393515
