### ISSUE TITLE
[Bug report] flutter beta 3.25 编译报错

### ISSUE THREAD

**Issue by davidche1116** [fluttercandies/extended_image#699]
### Version

8.2.1

### Platforms

dart

### Device Model

No

### flutter info

```sh
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
[!] Flutter (Channel beta, 3.25.0-0.1.pre, on Microsoft Windows [版本 10.0.22631.3958], locale zh-CN)
    • Flutter version 3.25.0-0.1.pre on channel beta at C:\fvm\default
    ! Warning: `flutter` on your path resolves to C:\fvm\versions\beta\bin\flutter, which is not inside your current Flutter SDK checkout at C:\fvm\default. Consider adding C:\fvm\default\bin to the front of your path.
    ! Warning: `dart` on your path resolves to C:\fvm\versions\beta\bin\dart, which is not inside your current Flutter SDK checkout at C:\fvm\default. Consider adding C:\fvm\default\bin to the front of your path.
    • Upstream repository https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • FLUTTER_GIT_URL = https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
    • Framework revision d3733fcb0e (11 hours ago), 2024-08-21 10:27:04 -0500
    • Engine revision 062b3a72fc
    • Dart version 3.6.0 (build 3.6.0-149.3.beta)
    • DevTools version 2.38.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: C:\Program Files\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/to/windows-android-setup for detailed instructions).

[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2022.3.2
    • Flutter plugin version 81.1.3
    • Dart plugin version 242.20629

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.22631.3958]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 127.0.2651.105

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 3 categories.
Process finished with exit code 0
```

### How to reproduce?

使用Flutter  Channel beta, 3.25.0-0.1.pre

### Logs

```sh
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _DragGestureRecognizer extends DragGestureRecognizer {
                                              ^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:615:7: Error: The non-abstract class '_VerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _VerticalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:676:7: Error: The non-abstract class '_HorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _HorizontalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:128:7: Error: The non-abstract class 'ExtendedHorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedHorizontalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:141:7: Error: The non-abstract class 'ExtendedVerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedVerticalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildCheRelease'.
> Process 'command 'C:\fvm\default\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 45s
Running Gradle task 'assembleCheRelease'...                        46.2s
Gradle task assembleCheRelease failed with exit code 1
BuildError: Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
注: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\mirrors.tuna.tsinghua.edu.cn%47dart-pub%47\android_intent_plus-5.1.0\android\src\main\java\dev\fluttercommunity\plus\androidintent\MethodCallHandlerImpl.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\mirrors.tuna.tsinghua.edu.cn%47dart-pub%47\vibration-2.0.0\android\src\main\java\com\benjaminabel\vibration\VibrationPlugin.java使用或覆了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _DragGestureRecognizer extends DragGestureRecognizer {
                                              ^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:615:7: Error: The non-abstract class '_VerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _VerticalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:676:7: Error: The non-abstract class '_HorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _HorizontalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:128:7: Error: The non-abstract class 'ExtendedHorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedHorizontalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:141:7: Error: The non-abstract class 'ExtendedVerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedVerticalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildCheRelease'.
> Process 'command 'C:\fvm\default\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 45s
Gradle task assembleCheRelease failed with exit code 1

#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:152:27)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:329:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>


RELEASE FAILED in 50s
BuildError: Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
注: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\mirrors.tuna.tsinghua.edu.cn%47dart-pub%47\android_intent_plus-5.1.0\android\src\main\java\dev\fluttercommunity\plus\androidintent\MethodCallHandlerImpl.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
注: C:\Users\Administrator\AppData\Local\Pub\Cache\hosted\mirrors.tuna.tsinghua.edu.cn%47dart-pub%47\vibration-2.0.0\android\src\main\java\com\benjaminabel\vibration\VibrationPlugin.java使用或覆了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Flutter assets will be downloaded from https://mirrors.tuna.tsinghua.edu.cn/flutter. Make sure you trust this source!
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
abstract class _DragGestureRecognizer extends DragGestureRecognizer {
                                              ^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:615:7: Error: The non-abstract class '_VerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _VerticalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/official.dart:676:7: Error: The non-abstract class '_HorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _HorizontalDragGestureRecognizer extends _DragGestureRecognizer {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:128:7: Error: The non-abstract class 'ExtendedHorizontalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedHorizontalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/Users/Administrator/AppData/Local/Pub/Cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/extended_image-8.2.1/lib/src/gesture_detector/drag_gesture_recognizer.dart:141:7: Error: The non-abstract class 'ExtendedVerticalDragGestureRecognizer' is missing implementations for these members:
 - DragGestureRecognizer.considerFling
 - DragGestureRecognizer.hasSufficientGlobalDistanceToAccept
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedVerticalDragGestureRecognizer
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:341:19: Context: 'DragGestureRecognizer.considerFling' is defined here.
  DragEndDetails? considerFling(VelocityEstimate estimate, PointerDeviceKind kind);
                  ^^^^^^^^^^^^^
/C:/fvm/default/packages/flutter/lib/src/gestures/monodrag.dart:370:8: Context: 'DragGestureRecognizer.hasSufficientGlobalDistanceToAccept' is defined here.
  bool hasSufficientGlobalDistanceToAccept(PointerDeviceKind pointerDeviceKind, double? deviceTouchSlop);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildCheRelease'.
> Process 'command 'C:\fvm\default\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 45s
Gradle task assembleCheRelease failed with exit code 1

#0      AppBuilder.build (package:flutter_app_builder/src/builders/app_builder.dart:68:7)
<asynchronous suspension>
#1      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:152:27)
<asynchronous suspension>
#2      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:329:45)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
```

**Comment by zmtzawqlp** [comment]
https://github.com/flutter/flutter/pull/151627

**Comment by no-chili** [comment]
@davidche1116 @zmtzawqlp 
```
Error (Xcode): ../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image-8.2.2/lib/src/gesture_detector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.

Could not build the application for the simulator.
Error launching application on iPhone 12.
```
有办法解决吗？

**Comment by davidche1116** [comment]
> @davidche1116 @zmtzawqlp
> 
> ```
> Error (Xcode): ../../../../.pub-cache/hosted/pub.flutter-io.cn/extended_image-8.2.2/lib/src/gesture_detector/official.dart:34:47: Error: The class 'DragGestureRecognizer' can't be extended, implemented, or mixed in outside of its library because it's a sealed class.
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 12.
> ```
> 
> 有办法解决吗？

@no-chili 降级Flutter到stable版本，先暂时不用beta版本和master版

**Comment by zmtzawqlp** [comment]
请更新到 8.2.3
